### ISSUE TITLE
[Feature Request] Support for outline

### ISSUE THREAD

**Issue by NaiveONe2** [dullage/flatnotes#151] opened 2024-01-25 15:09 UTC
Flatnote is a simple and fantastic note taking software. If the outline can be supported, operation of  reading and editing long texts will be more convenient.

**Comment by dullage** [comment] 2024-01-26 12:20
Hi @NaiveONe2 👋. There is a similar suggestion for this (#34) so I'll close this as a duplicate of that. Please go and give that a thumbs up to register your interest.

**Closed by dullage** 2024-01-26 12:20 UTC
