### ISSUE TITLE
Possibility to attach any type of file

### ISSUE THREAD

**Issue by dobrKot** [dullage/flatnotes#255] opened 2024-10-25 12:25 UTC
Is it possible to implement not only images attachments but any file attachment? If UI is not able to proccess/display it then make it as downloadable link to the file system.

**Comment by dullage** [comment] 2024-10-26 10:00
Unfortunately this isn't currently possible but is fairly commonly suggested.

This is a duplicate of #134 so please go give that issue a thumbs up to record your interest.

**Closed** 2024-10-26 10:01 UTC
Labels: duplicate
