### ISSUE TITLE
Suggestion: simple multi users

### ISSUE THREAD

**Issue by romu70** [dullage/flatnotes#128] opened 2023-10-07 13:49 UTC
I know the Flatnotes principle is KISS.

A simple proposition to provide multi-users would be to leverage the existing setup: by using environment variables.

In the docker-compose, we could imagine something like:

- FLATNOTES_USERS: 2
- FLATNOTES_USER1: « user1 »
- FLATNOTES_USER1_PASSWORD: « dkjfhsjfhsdjfhks »
- FLATNOTES_USER2: « user2 »
- FLATNOTES_USER2_PASSWORD: « sgfdqhfqsdfqhf »

I think providing such a feature would be great, and limiting to, let’s say, 5 users accounts max would be enough for a lot of people.

For each user, Flatnotes would create a new folder in the data volume. And everything will be as similar as of today.

**Comment by dullage** [comment] 2023-10-08 07:16
It's not a bad idea but you could also just run multiple instances of flatnotes and achieve the same thing. The additional overhead would be negligible.

**Comment by romu70** [comment] 2023-10-08 07:29
Yes, indeed. But that’s more work to setup this on the user side.

And my suggestion is more work on your side, I agree ;)

**Comment by weilah** [comment] 2023-10-10 19:39
I think this would be really a great feature to add. The overhead is not that negligible if a revers proxy route has to be setup for each instance of flatnotes.

**Comment by dullage** [comment] 2023-10-16 14:44
Closing as duplicate of #36. Please give that issue a thumbs up.

**Closed by dullage** 2023-10-16 14:44 UTC
