### ISSUE TITLE
Allow linking of sections in note

### ISSUE THREAD

**Issue by pbogre** [dullage/flatnotes#83] opened 2023-06-22 14:47 UTC
For example how github does it, where you can link a certain section of a note by using `#section-name` as the link on a regular link format, like this: `[section a](#a)` where `a` is the title of some section. 

This would allow indexes for notes with various sections

**Comment by dullage** [comment] 2023-06-23 16:12
I would like to do this. It's a dupe of #34 though so I'll close this off in favour of that. Please give the other issue a thumbs up so I can track interest.

**Closed by dullage** 2023-06-23 16:12 UTC
