### ISSUE TITLE
Cards 

### ISSUE THREAD

**Issue by MyWay** [dullage/flatnotes#79] opened 2023-06-03 23:49 UTC
Hi, as there is quite a bit of space in the layout, what do you think about making the 'home' a bit more like Google keep, with cards showing a bit of text?

Just found this is a duplicate of #57.

**Comment by dullage** [comment] 2023-06-04 07:56
Hi @MyWay, thanks for the suggestion. Personally, I'm keen on sticking with the clean/simple home page but I'm open to having my mind changed if there's strong enough interest. As you say, this is a duplicate of #57 so I'll close this off in favour of that. Please give that issue a thumbs up so I can track interest.

**Closed by dullage** 2023-06-04 07:56 UTC
