### ISSUE TITLE
Auto-generate title from timestamp

### ISSUE THREAD

**Issue by zemmyang** [dullage/flatnotes#239] opened 2024-09-08 05:34 UTC
**Feature request**:

It would be nice to be able to just generate a note using the current timestamp, either have it turned on in the setting automatically, or have a button that generates a timestamped title for the current note.

I currently put in the dates manually and it's a bit of a chore.

**Comment by dullage** [comment] 2024-09-10 11:49
This is a duplicate of #64, please give that issue a thumbs up to register your support.

**Closed by dullage** 2024-09-10 11:49 UTC
