### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by monkeyx-net** [dullage/flatnotes#256] opened 2024-10-26 07:21 UTC
Just started using this great project yesterday and really liking it.

Could I add my vote to include embedding files into notes.

~I had a typo in a tag name and it still shows up after correcting the error.~

~Is it possible to delete a tag reference?~

had a look at the code and could see a reference to indexing. So restarted the container to reindex :)

**Comment by dullage** [comment] 2024-10-26 10:05
Hey @monkeyx-net, glad you like flatnotes and glad you found the solution to the orphaned tag. Optimising the index (to remove orphaned tags) is expensive (takes time) so is only done on container start. 

As for attachments, unfortunately this isn't currently possible but is fairly commonly suggested.

This is a duplicate of #134 so please go give that issue a thumbs up to record your interest.

**Closed** 2024-10-26 10:05 UTC
Labels: question, duplicate
