### ISSUE TITLE
Keyboard Shortcut to Save a Note

### ISSUE THREAD

**Issue by houserockr** [dullage/flatnotes#59] opened 2023-04-01 12:04 UTC
Is there a way to overwrite the keyboard shortcuts of the toast-ui editor?

I found an attempt of using `ctrl+s` in the `created` function in `NoteViewEditor.vue` that has been commented out - understandably.

If I turn off the toast-ui shortcuts via `editorOptions: { useCommandShortcut: false }` (in `NoteViewerEditor.vue:206` - defaults to `true`) and enable the `Mousetrap` binding for `ctrl+s` (in `NoteViewerEditor.vue:528`), the editor shortcuts do indeed stop working, but the `Mousetrap` bindings don't work either. If you press `ctrl+s`, the event is simply passed through to the browser and it attempts to save the entire page as an html file.

**Comment by Dullage** [comment] 2023-04-01 14:19
I'm sure this will be possible but alas, it has confounded me so far (as you've seen from my commented attempt). 

I haven't spent too much time looking into it so when I get the chance I'll take another look.

**Comment by Mladia** [comment] 2023-08-22 20:29
I think this feature can be split into two parts. First part is a fast save function --- this will send a request to the server this will save the note, without going back to the overview

So, catching a 1) keypress in javascript,  2) collecting current Note name and Note text and 3) sending  a patch request to /api/notes/Notename. All of this is just client side.

If you tell me which files to look for each 1), 2) and 3) that are relevant, I can take a look as well.

**Comment by dullage** [comment] 2023-08-25 06:00
> I think this feature can be split into two parts. First part is a fast save function --- this will send a request to the server this will save the note, without going back to the overview
> 
> So, catching a 1) keypress in javascript, 2) collecting current Note name and Note text and 3) sending a patch request to /api/notes/Notename. All of this is just client side.
> 
> If you tell me which files to look for each 1), 2) and 3) that are relevant, I can take a look as well.

I like the idea of having an option to save without closing. But please raise a separate suggestion for this and I'll add some notes there.

Regarding the keyboard shortcut, the trouble I'm having is that the markdown editor I'm using (Toast UI Editor) is capturing the keypresses and not bubbling them up to my code. I've previously tried `ctrl+s` but the editor is using this for strikethrough. I've just tried `ctrl+enter` and although this doesn't appear to be used by the editor, it's still not bubbling up. It needs more digging.

**Comment by jokob-sk** [comment] 2024-06-21 01:59
Same here - would be great to have a shortcut to save (e.g. ctrl+shift+s, ctrl+shift+enter) - or the auto-save alternative

**Comment by marcxm** [comment] 2024-07-06 07:26
Indeed. Would be great to be able to save notes by using keyboard shortcut.

**Comment by dullage** [comment] 2024-07-06 07:33
A couple of days ago I merged a change into the develop branch that allows for notes to be saved without closing the note. 

Additionally, I've added 2 new keyboard shortcuts available when editing a note:

`CTRL-Enter` - Save (without closing)
`Escape` - Close the note

If anyone wants to give this a go before release you can pull and run the `dullage/flatnotes:develop` image.

**Comment by marcxm** [comment] 2024-07-06 11:40
Tested it today with develop docker image and I can confirm it works as intended. Thank you! great work.

**Comment by dullage** [comment] 2024-07-07 10:12
This change is now available in [5.2.0](https://github.com/dullage/flatnotes/releases/tag/v5.2.0). 🚀

**Closed by dullage** 2024-07-07 10:12 UTC
Labels: enhancement, help needed
