### ISSUE TITLE
Please add support for Markdown document outlines or [TOC]

### ISSUE THREAD

**Issue by mailguest** [dullage/flatnotes#149] opened 2023-12-29 07:23 UTC
Please add support for Markdown document outlines or [TOC]

**Comment by dullage** [comment] 2023-12-29 08:14
Thanks for the suggestion. This is a dupe of #34 so I'll close this in favour of that. Please go give that issue a thumbs up to log your interest.

**Closed by dullage** 2023-12-29 08:14 UTC
