### ISSUE TITLE
Add a toggle to enable a Table of Contents? 

### ISSUE THREAD

**Issue by CDubs00** [dullage/flatnotes#247] opened 2024-09-23 14:38 UTC
For larger notes I’d like to see a toggle at the top to enable a ToC on the left side of the page.

**Comment by dullage** [comment] 2024-09-23 15:05
This is very similar to #34 so I'll close this as a duplicate of that. Please give that issue a thumbs up to show your interest.

**Closed by dullage** 2024-09-23 15:05 UTC
