### ISSUE TITLE
Slash in title results in server error on save

### ISSUE THREAD

**Issue by dominikheinz** [Dullage/flatnotes#53] opened 2023-03-17 03:41 UTC
**Overview:**
Creating a new note with a title that contains a slash (`/`) character, gives an error "Unable to communicate with the server".
I have not debugged the problem or checked the code, but I assume the title is used as part of a filename, and the slash messes up the path?

**Suggestions:**
- Escape the slash character so saving is possible
- Provide a more meaningful error message, such as: Invalid characters in the title. Allowed characters are [a-z][A-Z] etc...
- If the title is indeed used as a file path, maybe rethink this idea by having a unique randomly generated ID associated with the note and use that instead.

**Comment by Dullage** [comment] 2023-03-17 06:25
Hi @dominikheinz. Your assumption is correct, this is a limitation of using the titles as filenames. This is a duplicate of #52 and there's a bit more detail on there. 

I really should be validating this in the front end as well (with a friendly message as you suggest). I'll add this in the next release.

**Comment by Dullage** [comment] 2023-03-17 12:42
A friendly message has been added in v2.2.0.

**Closed by Dullage** 2023-03-17 12:42 UTC
