### ISSUE TITLE
Add attachments

### ISSUE THREAD

**Issue by dd0ke** [dullage/flatnotes#262] opened 2024-11-18 12:08 UTC
I love the project, and the value of doing one thing, and doing it well.

I'd like to suggest a feature I'd find particularly useful: uploading any kind of attachments (besides images alone).

I have not yet looked into the code and perhaps could be able to provide that contribution directly, but it is going to be physically impossible for me in the upcoming days / weeks. 

If the feature speaks for itself, I'd be grateful to you to take it under consideration. Of course, a potential evolution of it would be to full-text-search attachments, but that isn't a must-have' prerogative to me at the moment.

I'm very interested in Flatnotes to securely share notes, and with attachments, a sort of knowledge base!

**Comment by dullage** [comment] 2024-11-18 18:44
Hey @dd0ke. I'm glad you're enjoying the project. This is a duplicate of #134, so I'll close this in favour of that. Please go give that suggestion a thumbs up to register your interest.

**Closed by dullage** 2024-11-18 18:44 UTC
